### ISSUE TITLE
Init Angular Dart project for Console web app

### ISSUE THREAD

**Issue by theanurin** [edgebus/edgebus#1]
# Init Angular Dart project for Console web app

Target branch: src/dart/console

## Todo

- [ ] Minimal compilable Dart application (for latest Dart SDK).
- [ ] Metronic dashboard backend.
- [ ] CI pipeline to build Docker image with standalone NGinx hosting for the application.

**Comment by theanurin** [comment]
Angular Dart completely died... So close this issue in flavour to #11
