### ISSUE TITLE
Draw few diagrams that shown common use-cases

### ISSUE THREAD

**Issue by theanurin** [edgebus/edgebus#13]
# Draw few diagrams that shown common use-cases

## To-do

- [ ] Look/Play with https://app.diagrams.net/ (if not familiar yet)
- [ ] Draw `diagram-1` that show general communication between Some Service and Webhook Data Vendor
- [ ] Draw `diagram-2` based on `diagram-1` but with EdgeBus Service in the middle of communication channel

## Expected Result (in docs branch)

```text
docs/assets/
├── diagram
│   ├── diagram-0001.drawio
│   ├── diagram-0001.png
│   ├── diagram-0002.drawio
│   └── diagram-0002.png
└── images
    ├── ...
    └── ...
```

## References
![IMG_0490](https://github.com/edgebus/edgebus/assets/22301243/6605ae19-533d-4c5c-9cea-57c45e7d9748)
![IMG_0491](https://github.com/edgebus/edgebus/assets/22301243/e6a1fe5e-232c-4841-9f1b-59869d5f08a2)
![IMG_0492](https://github.com/edgebus/edgebus/assets/22301243/7d2226d1-ddd8-41c4-bdba-eecb393c3f30)
![IMG_0493](https://github.com/edgebus/edgebus/assets/22301243/638cb0d2-5156-4c2c-9231-43deee44e115)
