### ISSUE TITLE
Init Dart SDK library

### ISSUE THREAD

**Issue by theanurin** [edgebus/edgebus#4]
# Init Dart SDK library

Target branch: `src-dart-sdk`

## Todo

- [ ] Minimal Dart library (for Dart SDK starts from 2.13.0)
- [ ] Cover few methods of backend API (for example topic management: create/fetch/list/modify) via APIs:
    - [ ] RESTFul
    - [ ] WebSocket
- [ ] CI pipeline to build and publish library to https://pub.dev
